[package]
name = "dsat"
version = "0.1.0"
authors = ["dan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-test = "0.2.1"
serial_test = "*"
rocket = "0.4.2"
rocket_cors = "0.5.2"
